sudo: false
dist: trusty
language: rust
cache: cargo
rust: nightly-2019-05-09 # minimum required version for async/await

before_install:
  - cargo install mdbook --vers '0.3.1' --debug --force
  - cargo install mdbook-linkcheck --vers '0.3.1' --debug --force

script:
  - rm -rf ./src
  - mv ./src_zh ./src
  - mdbook build
  - cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target

branches:
  only:
    - zh-CN
env:
  RUSTINFRA_DEPLOY_DIR: book/html
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: zh-CN
