[book]
title = "Asynchronous Programming in Rust"
authors = ["Taylor Cramer"]

[build]
create-missing = true

[preprocess.links]

[output.html]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
